List<String> verbs = [
  "insert into verbs (ru,en) values('быть','be')",
  "insert into verbs (ru,en) values('жить','live')",
  "insert into verbs (ru,en) values('иметь','have')",
  "insert into verbs (ru,en) values('значить','mean')",
  "insert into verbs (ru,en) values('держать','hold')",
  "insert into verbs (ru,en) values('сказать','say')",
  "insert into verbs (ru,en) values('мочь','able')",
  "insert into verbs (ru,en) values('говорить','say')",
  "insert into verbs (ru,en) values('знать','know')",
  "insert into verbs (ru,en) values('стать','become')",
  "insert into verbs (ru,en) values('есть','eat,be')",
  "insert into verbs (ru,en) values('хотеть','want')",
  "insert into verbs (ru,en) values('видеть','see')",
  "insert into verbs (ru,en) values('идти','go')",
  "insert into verbs (ru,en) values('стоять','stand')",
  "insert into verbs (ru,en) values('думать','think')",
  "insert into verbs (ru,en) values('спросить','ask')",
  "insert into verbs (ru,en) values('смотреть','look')",
  "insert into verbs (ru,en) values('сидеть','sit')",
  "insert into verbs (ru,en) values('понять','understand')",
  "insert into verbs (ru,en) values('делать','do')",
  "insert into verbs (ru,en) values('взять','take')",
  "insert into verbs (ru,en) values('сделать','do')",
  "insert into verbs (ru,en) values('понимать','understand')",
  "insert into verbs (ru,en) values('казаться','seem')",
  "insert into verbs (ru,en) values('давать','give')",
  "insert into verbs (ru,en) values('пойти','go')",
  "insert into verbs (ru,en) values('увидеть','see')",
  "insert into verbs (ru,en) values('остаться','remain')",
  "insert into verbs (ru,en) values('выйти','go out')",
  "insert into verbs (ru,en) values('дать','give')",
  "insert into verbs (ru,en) values('работать','work')",
  "insert into verbs (ru,en) values('любить','love')",
  "insert into verbs (ru,en) values('оказаться','turn up')",
  "insert into verbs (ru,en) values('ответить','answer')",
  "insert into verbs (ru,en) values('подумать','think')",
  "insert into verbs (ru,en) values('посмотреть','take a look')",
  "insert into verbs (ru,en) values('ждать','wait')",
  "insert into verbs (ru,en) values('лежать','lie')",
  "insert into verbs (ru,en) values('найти','find')",
  "insert into verbs (ru,en) values('писать','write')",
  "insert into verbs (ru,en) values('решить','decide')",
  "insert into verbs (ru,en) values('вернуться','return')",
  "insert into verbs (ru,en) values('считать','count')",
  "insert into verbs (ru,en) values('помнить','remember')",
  "insert into verbs (ru,en) values('получить','receive')",
  "insert into verbs (ru,en) values('ходить','go')",
  "insert into verbs (ru,en) values('бывать','heppen')",
  "insert into verbs (ru,en) values('прийти','come')",
  "insert into verbs (ru,en) values('узнать','know')",
  "insert into verbs (ru,en) values('заметить','notice')",
  "insert into verbs (ru,en) values('уйти','leave')",
  "insert into verbs (ru,en) values('слышать','hear')",
  "insert into verbs (ru,en) values('слушать','listen')",
  "insert into verbs (ru,en) values('бояться','be afraid')",
  "insert into verbs (ru,en) values('глядеть','look')",
  "insert into verbs (ru,en) values('сесть','sit')",
  "insert into verbs (ru,en) values('читать','read')",
  "insert into verbs (ru,en) values('оставаться','remain')",
  "insert into verbs (ru,en) values('брать','take')",
  "insert into verbs (ru,en) values('написать','write')",
  "insert into verbs (ru,en) values('начинать','begin')",
  "insert into verbs (ru,en) values('чувствовать','feel')",
  "insert into verbs (ru,en) values('вести','lead')",
  "insert into verbs (ru,en) values('успеть','be in time')",
  "insert into verbs (ru,en) values('продолжать','continue')",
  "insert into verbs (ru,en) values('забыть','forget')",
  "insert into verbs (ru,en) values('пройти','pass')",
  "insert into verbs (ru,en) values('появиться','appear')",
  "insert into verbs (ru,en) values('выходить','go out')",
  "insert into verbs (ru,en) values('просить','ask')",
  "insert into verbs (ru,en) values('пытаться','try')",
  "insert into verbs (ru,en) values('показать','show')",
  "insert into verbs (ru,en) values('вспомнить','remember')",
  "insert into verbs (ru,en) values('называть','call')",
  "insert into verbs (ru,en) values('уходить','leave')",
  "insert into verbs (ru,en) values('подойти','approach')",
  "insert into verbs (ru,en) values('поднять','lift')",
  "insert into verbs (ru,en) values('спрашивать','ask')",
  "insert into verbs (ru,en) values('бросить','throw')",
  "insert into verbs (ru,en) values('послать','send')",
  "insert into verbs (ru,en) values('находиться','be found')",
  "insert into verbs (ru,en) values('поставить','put')",
  "insert into verbs (ru,en) values('встать','get up')",
  "insert into verbs (ru,en) values('играть','play')",
  "insert into verbs (ru,en) values('следовать','follow')",
  "insert into verbs (ru,en) values('рассказать','tell')",
  "insert into verbs (ru,en) values('спать','sleep')",
  "insert into verbs (ru,en) values('оставить','leave')",
  "insert into verbs (ru,en) values('войти','enter')",
  "insert into verbs (ru,en) values('молчать','keep silence')",
  "insert into verbs (ru,en) values('рассказывать','tell')",
  "insert into verbs (ru,en) values('отвечать','answer')",
  "insert into verbs (ru,en) values('становиться','stand')",
  "insert into verbs (ru,en) values('остановиться','stop')",
  "insert into verbs (ru,en) values('искать','search')",
  "insert into verbs (ru,en) values('начать','begin')",
  "insert into verbs (ru,en) values('верить','believe')",
  "insert into verbs (ru,en) values('являться','appear')",
  "insert into verbs (ru,en) values('смочь','be able')",
  "insert into verbs (ru,en) values('бежать','run')",
  "insert into verbs (ru,en) values('приехать','arrive')",
  "insert into verbs (ru,en) values('кричать','cry')",
  "insert into verbs (ru,en) values('открыть','open')",
  "insert into verbs (ru,en) values('происходить','happen')",
  "insert into verbs (ru,en) values('ехать','go')",
  "insert into verbs (ru,en) values('приходить','come')",
  "insert into verbs (ru,en) values('подняться','rise')",
  "insert into verbs (ru,en) values('показаться','appear')",
  "insert into verbs (ru,en) values('собираться','gather together')",
  "insert into verbs (ru,en) values('попасть','hit')",
  "insert into verbs (ru,en) values('принять','take')",
  "insert into verbs (ru,en) values('поехать','depart')",
  "insert into verbs (ru,en) values('услышать','hear')",
  "insert into verbs (ru,en) values('уметь','be able')",
  "insert into verbs (ru,en) values('случиться','happen')",
  "insert into verbs (ru,en) values('стараться','try')",
  "insert into verbs (ru,en) values('звать','call')",
  "insert into verbs (ru,en) values('произойти','happen')",
  "insert into verbs (ru,en) values('заниматься','be occupied')",
  "insert into verbs (ru,en) values('положить','lay down')",
  "insert into verbs (ru,en) values('купить','buy')",
  "insert into verbs (ru,en) values('умереть','die')",
  "insert into verbs (ru,en) values('пить','drink')",
  "insert into verbs (ru,en) values('проходить','pass')",
  "insert into verbs (ru,en) values('снять','take away')",
  "insert into verbs (ru,en) values('начаться','begin')",
  "insert into verbs (ru,en) values('представлять','present')",
  "insert into verbs (ru,en) values('объяснить','explain')",
  "insert into verbs (ru,en) values('произнести','pronounce')",
  "insert into verbs (ru,en) values('нравиться','please')",
  "insert into verbs (ru,en) values('существовать','exist')",
  "insert into verbs (ru,en) values('удаться','succed')",
  "insert into verbs (ru,en) values('прийтись','fit')",
  "insert into verbs (ru,en) values('представить','present')",
  "insert into verbs (ru,en) values('назвать','call')",
  "insert into verbs (ru,en) values('улыбаться','smile')",
  "insert into verbs (ru,en) values('улыбнуться','smile')",
  "insert into verbs (ru,en) values('смеяться','laugh')",
  "insert into verbs (ru,en) values('хватать','snatch')",
  "insert into verbs (ru,en) values('почувствовать','feel')",
  "insert into verbs (ru,en) values('принести','bring')",
  "insert into verbs (ru,en) values('согласиться','agree')",
  "insert into verbs (ru,en) values('хватить','snatch')",
  "insert into verbs (ru,en) values('принимать','take')",
  "insert into verbs (ru,en) values('убить','kill')",
  "insert into verbs (ru,en) values('предложить','offer')",
  "insert into verbs (ru,en) values('приходиться','fit')",
  "insert into verbs (ru,en) values('выпить','drink')",
  "insert into verbs (ru,en) values('крикнуть','cry')",
  "insert into verbs (ru,en) values('показывать','show')",
  "insert into verbs (ru,en) values('вызвать','call')",
  "insert into verbs (ru,en) values('попросить','ask')",
  "insert into verbs (ru,en) values('оказываться','turn out')",
  "insert into verbs (ru,en) values('привести','bring')",
  "insert into verbs (ru,en) values('возвращаться','return')",
  "insert into verbs (ru,en) values('требовать','demand')",
  "insert into verbs (ru,en) values('потерять','lose')",
  "insert into verbs (ru,en) values('достать','reach')",
  "insert into verbs (ru,en) values('сообщить','report')",
  "insert into verbs (ru,en) values('появляться','appear')",
  "insert into verbs (ru,en) values('упасть','fall')",
  "insert into verbs (ru,en) values('получиться','come')",
  "insert into verbs (ru,en) values('провести','accompany')",
  "insert into verbs (ru,en) values('простить','forgive')",
  "insert into verbs (ru,en) values('бить','beat')",
  "insert into verbs (ru,en) values('кивнуть','nod')",
  "insert into verbs (ru,en) values('исчезнуть','disappear')",
  "insert into verbs (ru,en) values('отдать','return')",
  "insert into verbs (ru,en) values('помочь','help')",
  "insert into verbs (ru,en) values('слать','send imperfective')",
  "insert into verbs (ru,en) values('вспоминать','remember')",
  "insert into verbs (ru,en) values('вздохнуть','take breath,sigh')",
  "insert into verbs (ru,en) values('петь','sing')",
  "insert into verbs (ru,en) values('садиться','sit down')",
  "insert into verbs (ru,en) values('перестать','stop')",
  "insert into verbs (ru,en) values('придтись','fit')",
  "insert into verbs (ru,en) values('пожаловать','grant')",
  "insert into verbs (ru,en) values('получать','receive')",
  "insert into verbs (ru,en) values('называться','call oneself')",
  "insert into verbs (ru,en) values('надеяться','hope')",
  "insert into verbs (ru,en) values('протянуть','stretch')",
  "insert into verbs (ru,en) values('подходить','come up')",
  "insert into verbs (ru,en) values('служить','serve')",
  "insert into verbs (ru,en) values('поверить','believe')",
  "insert into verbs (ru,en) values('взглянуть','look')",
  "insert into verbs (ru,en) values('вызывать','call')",
  "insert into verbs (ru,en) values('ожидать','expect')",
  "insert into verbs (ru,en) values('висеть','hang imperfective')",
  "insert into verbs (ru,en) values('создать','create')",
  "insert into verbs (ru,en) values('уехать','leave')",
  "insert into verbs (ru,en) values('выглядеть','look imperfective')",
  "insert into verbs (ru,en) values('учиться','study')",
  "insert into verbs (ru,en) values('разговаривать','talk')",
  "insert into verbs (ru,en) values('помогать','help')",
  "insert into verbs (ru,en) values('повернуться','turn')",
  "insert into verbs (ru,en) values('позволить','allow')",
  "insert into verbs (ru,en) values('встретить','meet')",
  "insert into verbs (ru,en) values('входить','enter')",
  "insert into verbs (ru,en) values('обнаружить','discover')",
  "insert into verbs (ru,en) values('нести','carry')",
  "insert into verbs (ru,en) values('прислать','send')",
  "insert into verbs (ru,en) values('относиться','treat')",
  "insert into verbs (ru,en) values('возникать','arise')",
  "insert into verbs (ru,en) values('повторить','repeat')",
  "insert into verbs (ru,en) values('погибнуть','perish')",
  "insert into verbs (ru,en) values('гореть','burn')",
  "insert into verbs (ru,en) values('плакать','cry')",
  "insert into verbs (ru,en) values('двигаться','move')",
  "insert into verbs (ru,en) values('добавить','add')",
  "insert into verbs (ru,en) values('удивиться','wonder')",
  "insert into verbs (ru,en) values('действовать','act imperfective')",
  "insert into verbs (ru,en) values('держаться','hold on')",
  "insert into verbs (ru,en) values('лететь','fly imperfective')",
  "insert into verbs (ru,en) values('носить','wear')",
  "insert into verbs (ru,en) values('привыкнуть','get used to,grow accustomed to')",
  "insert into verbs (ru,en) values('позвонить','call,telephone')",
  "insert into verbs (ru,en) values('мешать','interfere')",
  "insert into verbs (ru,en) values('возникнуть','arise')",
  "insert into verbs (ru,en) values('желать','wish')",
  "insert into verbs (ru,en) values('попробовать','try')",
  "insert into verbs (ru,en) values('получаться','come out')",
  "insert into verbs (ru,en) values('ставить','put')",
  "insert into verbs (ru,en) values('проводить','lead')",
  "insert into verbs (ru,en) values('обещать','promise')",
  "insert into verbs (ru,en) values('судить','judge')",
  "insert into verbs (ru,en) values('собраться','gather')",
  "insert into verbs (ru,en) values('колоть','prick')",
  "insert into verbs (ru,en) values('закричать','shout')",
  "insert into verbs (ru,en) values('кончиться','end')",
  "insert into verbs (ru,en) values('стрелять','shoot')",
  "insert into verbs (ru,en) values('использовать','use')",
  "insert into verbs (ru,en) values('пахнуть','smell imperfective')",
  "insert into verbs (ru,en) values('передать','pass')",
  "insert into verbs (ru,en) values('вставать','get up')",
  "insert into verbs (ru,en) values('снимать','take off,photograph,rent снимать')",
  "insert into verbs (ru,en) values('звонить','ring')",
  "insert into verbs (ru,en) values('напоминать','remind')",
  "insert into verbs (ru,en) values('придумать','think')",
  "insert into verbs (ru,en) values('падать','fall')",
  "insert into verbs (ru,en) values('поговорить','have a talk')",
  "insert into verbs (ru,en) values('начинаться','begin')",
  "insert into verbs (ru,en) values('приказать','order')",
  "insert into verbs (ru,en) values('засмеяться','start laughing')",
  "insert into verbs (ru,en) values('касаться','touch')",
  "insert into verbs (ru,en) values('приняться','begin')",
  "insert into verbs (ru,en) values('заставить','force')",
  "insert into verbs (ru,en) values('подниматься','rise')",
  "insert into verbs (ru,en) values('ударить','strike')",
  "insert into verbs (ru,en) values('разуметься','be understood imperfective')",
  "insert into verbs (ru,en) values('встречаться','meet')",
  "insert into verbs (ru,en) values('попытаться','try')",
  "insert into verbs (ru,en) values('схватить','seize')",
  "insert into verbs (ru,en) values('отказаться','decline')",
  "insert into verbs (ru,en) values('вытащить','take out')",
  "insert into verbs (ru,en) values('предлагать','offer')",
  "insert into verbs (ru,en) values('отправиться','set off')",
  "insert into verbs (ru,en) values('побежать','start running,run perfective')",
  "insert into verbs (ru,en) values('курить','smoke')",
  "insert into verbs (ru,en) values('открывать','open')",
  "insert into verbs (ru,en) values('зайти','come in')",
  "insert into verbs (ru,en) values('замечать','notice')",
  "insert into verbs (ru,en) values('закончить','end')",
  "insert into verbs (ru,en) values('следить','watch')",
  "insert into verbs (ru,en) values('броситься','throw oneself')",
  "insert into verbs (ru,en) values('закрыть','close')",
  "insert into verbs (ru,en) values('понравиться','like (as in \"I liked\")')",
  "insert into verbs (ru,en) values('обратиться','appeal')",
  "insert into verbs (ru,en) values('велеть','order')",
  "insert into verbs (ru,en) values('иметься','have')",
  "insert into verbs (ru,en) values('опустить','lower')",
  "insert into verbs (ru,en) values('родиться','be born')",
  "insert into verbs (ru,en) values('спасти','save')",
  "insert into verbs (ru,en) values('извинить','excuse')",
  "insert into verbs (ru,en) values('объявить','declare')",
  "insert into verbs (ru,en) values('обращаться','appeal')",
  "insert into verbs (ru,en) values('спешить','hurry')",
  "insert into verbs (ru,en) values('наблюдать','observe')",
  "insert into verbs (ru,en) values('суметь','be able')",
  "insert into verbs (ru,en) values('обернуться','turn out')",
  "insert into verbs (ru,en) values('проснуться','wake up')",
  "insert into verbs (ru,en) values('подождать','wait')",
  "insert into verbs (ru,en) values('заговорить','begin speak')",
  "insert into verbs (ru,en) values('пользоваться','use')",
  "insert into verbs (ru,en) values('повторять','repeat')",
  "insert into verbs (ru,en) values('учить','teach')",
  "insert into verbs (ru,en) values('взяться','set about')",
  "insert into verbs (ru,en) values('бегать','run')",
  "insert into verbs (ru,en) values('устроить','arrange,make')",
  "insert into verbs (ru,en) values('дышать','breathe imperfective')",
  "insert into verbs (ru,en) values('лечь','lie down')",
  "insert into verbs (ru,en) values('состоять','consist of')",
  "insert into verbs (ru,en) values('заходить','come in')",
  "insert into verbs (ru,en) values('считаться','take inconsideration')",
  "insert into verbs (ru,en) values('ездить','drive')",
  "insert into verbs (ru,en) values('остановить','stop')",
  "insert into verbs (ru,en) values('встретиться','meet')",
  "insert into verbs (ru,en) values('явиться','appear')",
  "insert into verbs (ru,en) values('привезти','bring')",
  "insert into verbs (ru,en) values('платить','pay')",
  "insert into verbs (ru,en) values('спасть','fall')",
  "insert into verbs (ru,en) values('здравствовать','be well')",
  "insert into verbs (ru,en) values('позволять','allow')",
  "insert into verbs (ru,en) values('заявить','declare')",
  "insert into verbs (ru,en) values('торчать','protrude')",
  "insert into verbs (ru,en) values('поймать','catch')",
  "insert into verbs (ru,en) values('собирать','gather')",
  "insert into verbs (ru,en) values('находить','find')",
  "insert into verbs (ru,en) values('собрать','gather')",
  "insert into verbs (ru,en) values('наступить','come')",
  "insert into verbs (ru,en) values('тянуть','pull')",
  "insert into verbs (ru,en) values('бросать','throw')",
  "insert into verbs (ru,en) values('мечтать','dream')",
  "insert into verbs (ru,en) values('захотеть','want,feel like')",
  "insert into verbs (ru,en) values('оставлять','leave')",
  "insert into verbs (ru,en) values('усмехнуться','give a short laugh')",
  "insert into verbs (ru,en) values('пропасть','disappear')",
  "insert into verbs (ru,en) values('выдержать','bear')",
  "insert into verbs (ru,en) values('встречать','meet')",
  "insert into verbs (ru,en) values('пускать','let')",
  "insert into verbs (ru,en) values('отпустить','let go')",
  "insert into verbs (ru,en) values('воскликнуть','exclaim')",
  "insert into verbs (ru,en) values('дрожать','tremble imperfective')",
  "insert into verbs (ru,en) values('выбрать','choose')",
  "insert into verbs (ru,en) values('пожать','press,reap')",
  "insert into verbs (ru,en) values('раздаться','be heard')",
  "insert into verbs (ru,en) values('объяснять','explain')",
  "insert into verbs (ru,en) values('сунуть','shove')",
  "insert into verbs (ru,en) values('разрешить','allow')",
  "insert into verbs (ru,en) values('признаться','confess')",
  "insert into verbs (ru,en) values('составлять','make up')",
  "insert into verbs (ru,en) values('видать','see imperfective')",
  "insert into verbs (ru,en) values('занимать','borrow')",
  "insert into verbs (ru,en) values('терять','lose')",
  "insert into verbs (ru,en) values('вскочить','jump')",
  "insert into verbs (ru,en) values('прочитать','read')",
  "insert into verbs (ru,en) values('лезть','get in,push')",
  "insert into verbs (ru,en) values('отправить','send')",
  "insert into verbs (ru,en) values('построить','build')",
  "insert into verbs (ru,en) values('пустить','let in,let go')",
  "insert into verbs (ru,en) values('заглянуть','peep in')",
  "insert into verbs (ru,en) values('проговорить','say')",
  "insert into verbs (ru,en) values('проверить','check')",
  "insert into verbs (ru,en) values('болеть','be ill')",
  "insert into verbs (ru,en) values('поднимать','raise')",
  "insert into verbs (ru,en) values('означать','mean')",
  "insert into verbs (ru,en) values('говориться','be said imperfective')",
  "insert into verbs (ru,en) values('испытывать','try')",
  "insert into verbs (ru,en) values('жениться','marry imperf')",
  "insert into verbs (ru,en) values('оглянуться','look back')",
  "insert into verbs (ru,en) values('пригласить','invite')",
  "insert into verbs (ru,en) values('принадлежать','belong imperfective')",
  "insert into verbs (ru,en) values('строить','build')",
  "insert into verbs (ru,en) values('перейти','cross')",
  "insert into verbs (ru,en) values('повезти','be lucky,convery')",
  "insert into verbs (ru,en) values('поглядеть','look')",
  "insert into verbs (ru,en) values('повернуть','turn')",
  "insert into verbs (ru,en) values('добраться','arrive')",
  "insert into verbs (ru,en) values('признать','recognize')",
  "insert into verbs (ru,en) values('поступить','enter')",
  "insert into verbs (ru,en) values('торопиться','be in a hurry')",
  "insert into verbs (ru,en) values('вынуть','take out')",
  "insert into verbs (ru,en) values('стоить','cost')",
  "insert into verbs (ru,en) values('полагать','suppose')",
  "insert into verbs (ru,en) values('послушать','listen to')",
  "insert into verbs (ru,en) values('отметить','mark')",
  "insert into verbs (ru,en) values('утверждать','affirm')",
  "insert into verbs (ru,en) values('отличаться','differ')",
  "insert into verbs (ru,en) values('выскочить','jump out')",
  "insert into verbs (ru,en) values('приезжать','arrive')",
  "insert into verbs (ru,en) values('катить','drive')",
  "insert into verbs (ru,en) values('расти','grow imperfective')",
  "insert into verbs (ru,en) values('вернуть','return')",
  "insert into verbs (ru,en) values('зависеть','depend imperfective')",
  "insert into verbs (ru,en) values('познакомиться','meet')",
  "insert into verbs (ru,en) values('жалить','sting')",
  "insert into verbs (ru,en) values('найтись','be found')",
  "insert into verbs (ru,en) values('делаться','become')",
  "insert into verbs (ru,en) values('догадаться','guess,have the sense to')",
  "insert into verbs (ru,en) values('прожить','live')",
  "insert into verbs (ru,en) values('гулять','go for a walk')",
  "insert into verbs (ru,en) values('разобраться','disassemble,look into')",
  "insert into verbs (ru,en) values('отдавать','return')",
  "insert into verbs (ru,en) values('сходить','go and get,go down')",
  "insert into verbs (ru,en) values('звучать','sound')",
  "insert into verbs (ru,en) values('волноваться','worry')",
  "insert into verbs (ru,en) values('подать','give')",
  "insert into verbs (ru,en) values('готовить','prepare')",
  "insert into verbs (ru,en) values('жалеть','feel sorry')",
  "insert into verbs (ru,en) values('врать','lie')",
  "insert into verbs (ru,en) values('возразить','object')",
  "insert into verbs (ru,en) values('готовиться','prepare for')",
  "insert into verbs (ru,en) values('превратиться','change into')",
  "insert into verbs (ru,en) values('терпеть','endure')",
  "insert into verbs (ru,en) values('махнуть','wave')",
  "insert into verbs (ru,en) values('определить','define')",
  "insert into verbs (ru,en) values('выпустить','let out')",
  "insert into verbs (ru,en) values('выступать','come forward')",
  "insert into verbs (ru,en) values('рассматривать','look at')",
  "insert into verbs (ru,en) values('отойти','go away')",
  "insert into verbs (ru,en) values('вырасти','grow')",
  "insert into verbs (ru,en) values('перевести','transfer')",
  "insert into verbs (ru,en) values('посадить','plant')",
  "insert into verbs (ru,en) values('орать','shout')",
  "insert into verbs (ru,en) values('обойтись','treat,cost')",
  "insert into verbs (ru,en) values('выдать','hand')",
  "insert into verbs (ru,en) values('воевать','be at war,fight')",
  "insert into verbs (ru,en) values('останавливаться','stop')",
  "insert into verbs (ru,en) values('обладать','have')",
  "insert into verbs (ru,en) values('продать','sell')",
  "insert into verbs (ru,en) values('спорить','argue')",
  "insert into verbs (ru,en) values('выполнять','fulfill')",
  "insert into verbs (ru,en) values('требоваться','be required')",
  "insert into verbs (ru,en) values('умирать','die')",
  "insert into verbs (ru,en) values('дойти','reach')",
  "insert into verbs (ru,en) values('успокоиться','calm down')",
  "insert into verbs (ru,en) values('приближаться','approach')",
  "insert into verbs (ru,en) values('летать','fly')",
  "insert into verbs (ru,en) values('убивать','kill')",
  "insert into verbs (ru,en) values('двинуться','move')",
  "insert into verbs (ru,en) values('спуститься','come down')",
  "insert into verbs (ru,en) values('установить','install')",
  "insert into verbs (ru,en) values('забывать','forget')",
  "insert into verbs (ru,en) values('позвать','call')",
  "insert into verbs (ru,en) values('испугаться','be frightened')",
  "insert into verbs (ru,en) values('съесть','eat')",
  "insert into verbs (ru,en) values('прочесть','read')",
  "insert into verbs (ru,en) values('задуматься','ponder')",
  "insert into verbs (ru,en) values('решать','decide,solve')",
  "insert into verbs (ru,en) values('подарить','give (as a present')",
  "insert into verbs (ru,en) values('измениться','change')",
  "insert into verbs (ru,en) values('приводить','bring')",
  "insert into verbs (ru,en) values('удивляться','be surprised')",
  "insert into verbs (ru,en) values('забрать','take away')",
  "insert into verbs (ru,en) values('занять','take up')",
  "insert into verbs (ru,en) values('доказать','prove')",
  "insert into verbs (ru,en) values('варить','boil')",
  "insert into verbs (ru,en) values('изменить','change')",
  "insert into verbs (ru,en) values('ловить','catch,betray')",
  "insert into verbs (ru,en) values('стремиться','speed')",
  "insert into verbs (ru,en) values('тянуться','stretch')",
  "insert into verbs (ru,en) values('заставлять','force')",
  "insert into verbs (ru,en) values('страдать','suffer')",
  "insert into verbs (ru,en) values('записать','write down')",
  "insert into verbs (ru,en) values('интересовать','interest')",
  "insert into verbs (ru,en) values('включить','include,switch on')",
  "insert into verbs (ru,en) values('поразить','strike')",
  "insert into verbs (ru,en) values('помолчать','keep quiet')",
  "insert into verbs (ru,en) values('открыться','open')",
  "insert into verbs (ru,en) values('направить','direct')",
  "insert into verbs (ru,en) values('запомнить','memorize')",
  "insert into verbs (ru,en) values('бороться','struggle')",
  "insert into verbs (ru,en) values('везти','tranport,be lucky')",
  "insert into verbs (ru,en) values('научиться','learn')",
  "insert into verbs (ru,en) values('назначить','assign')",
  "insert into verbs (ru,en) values('выбирать','choose')",
  "insert into verbs (ru,en) values('напомнить','remind')",
  "insert into verbs (ru,en) values('сомневаться','doubt')",
  "insert into verbs (ru,en) values('радоваться','be glad')",
  "insert into verbs (ru,en) values('покрыть','cover')",
  "insert into verbs (ru,en) values('глянуть','glance')",
  "insert into verbs (ru,en) values('захватить','seize')",
  "insert into verbs (ru,en) values('приносить','bring')",
  "insert into verbs (ru,en) values('составить','compose')",
  "insert into verbs (ru,en) values('костить','abuse')",
  "insert into verbs (ru,en) values('покупать','buy')",
  "insert into verbs (ru,en) values('стучать','tap')",
  "insert into verbs (ru,en) values('менять','change')",
  "insert into verbs (ru,en) values('разглядывать','examine')",
  "insert into verbs (ru,en) values('закурить','light up')",
  "insert into verbs (ru,en) values('устать','get tired')",
  "insert into verbs (ru,en) values('прикрыть','cover')",
  "insert into verbs (ru,en) values('замолчать','stop talking,hush up')",
  "insert into verbs (ru,en) values('завести','bring')",
  "insert into verbs (ru,en) values('прибыть','arrive')",
  "insert into verbs (ru,en) values('подтвердить','confirm')",
  "insert into verbs (ru,en) values('сойти','come down,go and fetch')",
  "insert into verbs (ru,en) values('поступать','enter')",
  "insert into verbs (ru,en) values('валить','bring down')",
  "insert into verbs (ru,en) values('надоесть','bore')",
  "insert into verbs (ru,en) values('вывести','take out')",
  "insert into verbs (ru,en) values('прыгать','jump')",
  "insert into verbs (ru,en) values('создавать','create')",
  "insert into verbs (ru,en) values('убедиться','be convinced,make sure')",
  "insert into verbs (ru,en) values('ненавидеть','hate')",
  "insert into verbs (ru,en) values('исчезать','disappear')",
  "insert into verbs (ru,en) values('ощущать','feel')",
  "insert into verbs (ru,en) values('тащить','pull')",
  "insert into verbs (ru,en) values('скрывать','hide')",
  "insert into verbs (ru,en) values('совершить','accomplish')",
  "insert into verbs (ru,en) values('замереть','stand still')",
  "insert into verbs (ru,en) values('подавать','give')",
  "insert into verbs (ru,en) values('произвести','make')",
  "insert into verbs (ru,en) values('дождаться','wait till')",
  "insert into verbs (ru,en) values('плыть','swim')",
  "insert into verbs (ru,en) values('выполнить','implement')",
  "insert into verbs (ru,en) values('направиться','set off for')",
];
